/* eslint-disable operator-linebreak */
/* eslint-disable react/jsx-no-target-blank */
import React, { useState } from 'react';
import classBind from 'classnames/bind';
import styles from './styles.module.scss';

const cx = classBind.bind(styles);

export default function PageFooter() {
    const [isShowMoreLink, setIsShowMoreLink] = useState(false);
    // 致歉声明，7.6下午7点之后隐藏
    const [showApologize, setShowApologize] = useState(false);
    const superviseTime = () => {
        setTimeout(() => {
            const now = Date.now();
            if (now < new Date('2021/07/06 19:00:00').getTime()) {
                !showApologize && setShowApologize(true);
                superviseTime();
            } else {
                showApologize && setShowApologize(false);
            }
        }, 1000);
    };
    superviseTime();
    return (
        <div
            className={cx('footer-wrap')}
            id="jp-page-footer"
        >
            <div className={cx('links-wrap')}>
                <dl className={cx('links-list')}>
                    <dt>如何购买</dt>
                    <dd>
                        <a
                            className={cx('link')}
                            rel="nofollow"
                            target="_blank"
                            href="//help.koolearn.com/20131125/8.html"
                        >新用户注册
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            rel="nofollow"
                            target="_blank"
                            href="//help.koolearn.com/20131125/10.html"
                        >网上支付
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            rel="nofollow"
                            target="_blank"
                            href="//help.koolearn.com/20160408/54.html"
                        >京东白条购课
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            rel="nofollow"
                            target="_blank"
                            href="//help.koolearn.com/20160506/55.html"
                        >优惠券使用流程
                        </a>
                    </dd>
                </dl>
                <dl className={cx('links-list')}>
                    <dt>新生入学</dt>
                    <dd>
                        <a
                            className={cx('link')}
                            rel="nofollow"
                            target="_blank"
                            href="//help.koolearn.com/20131125/15.html"
                        >忘记密码
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            rel="nofollow"
                            target="_blank"
                            href="//help.koolearn.com/20160513/60.html"
                        >协议管理
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            rel="nofollow"
                            target="_blank"
                            href="//help.koolearn.com/20160513/59.html"
                        >如何听课
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            rel="nofollow"
                            target="_blank"
                            href="//help.koolearn.com/20160617/70.html"
                        >知识堂答疑
                        </a>
                    </dd>
                </dl>
                <dl className={cx('links-list')}>
                    <dt>听课问题</dt>
                    <dd>
                        <a
                            className={cx('link')}
                            rel="nofollow"
                            target="_blank"
                            href="//help.koolearn.com/20150427/46.html"
                        >APP如何安装
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            rel="nofollow"
                            target="_blank"
                            href="//help.koolearn.com/20150427/45.html"
                        >APP常见问题
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            rel="nofollow"
                            target="_blank"
                            href="//help.koolearn.com/20140226/39.html"
                        >视频无法打开
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            rel="nofollow"
                            target="_blank"
                            href="//help.koolearn.com/20131127/33.html"
                        >视频卡顿
                        </a>
                    </dd>
                </dl>
                <dl className={cx('links-list')}>
                    <dt>售后服务</dt>
                    <dd>
                        <a
                            className={cx('link')}
                            rel="nofollow"
                            target="_blank"
                            href="//help.koolearn.com/20131125/6.html"
                        >开具发票的事宜
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            rel="nofollow"
                            target="_blank"
                            href="//help.koolearn.com/20131127/32.html"
                        >如何休学
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            rel="nofollow"
                            target="_blank"
                            href="//help.koolearn.com/20131125/5.html"
                        >课程升级与操作方法说明
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            rel="nofollow"
                            target="_blank"
                            href="//help.koolearn.com/20131125/4.html"
                        >退换课规定
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            rel="nofollow"
                            target="_blank"
                            href="//help.koolearn.com/"
                        >更多问题
                        </a>
                    </dd>
                </dl>
                <dl className={cx('city-buy')}>
                    <dt>各地购课</dt>
                    <dd>
                        <a
                            className={cx('link')}
                            target="_blank"
                            href="//sc.koolearn.com/fen/service-centre/map/北京市"
                        >北京
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            target="_blank"
                            href="//sc.koolearn.com/fen/service-centre/map/天津市"
                        >天津
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            target="_blank"
                            href="//sc.koolearn.com/fen/service-centre/map/河北省"
                        >河北
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            target="_blank"
                            href="//sc.koolearn.com/fen/service-centre/map/山西省"
                        >山西
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            target="_blank"
                            href="//sc.koolearn.com/fen/service-centre/map/内蒙古自治区"
                        >内蒙古
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            target="_blank"
                            href="//sc.koolearn.com/fen/service-centre/map/辽宁省"
                        >辽宁
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            target="_blank"
                            href="//sc.koolearn.com/fen/service-centre/map/吉林省"
                        >吉林
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            target="_blank"
                            href="//sc.koolearn.com/fen/service-centre/map/黑龙江省"
                        >黑龙江
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            target="_blank"
                            href="//sc.koolearn.com/fen/service-centre/map/上海市"
                        >上海
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            target="_blank"
                            href="//sc.koolearn.com/fen/service-centre/map/江苏省"
                        >江苏
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            target="_blank"
                            href="//sc.koolearn.com/fen/service-centre/map/浙江省"
                        >浙江
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            href="//sc.koolearn.com/fen/service-centre/map/安徽省"
                            target="_blank"
                        >安徽
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            target="_blank"
                            href="//sc.koolearn.com/fen/service-centre/map/福建省"
                        >福建
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            target="_blank"
                            href="//sc.koolearn.com/fen/service-centre/map/江西省"
                        >江西
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            target="_blank"
                            href="//sc.koolearn.com/fen/service-centre/map/山东省"
                        >山东
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            target="_blank"
                            href="//sc.koolearn.com/fen/service-centre/map/河南省"
                        >河南
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            target="_blank"
                            href="//sc.koolearn.com/fen/service-centre/map/湖北省"
                        >湖北
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            target="_blank"
                            href="//sc.koolearn.com/fen/service-centre/map/湖南省"
                        >湖南
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            target="_blank"
                            href="//sc.koolearn.com/fen/service-centre/map/广东省"
                        >广东
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            target="_blank"
                            href="//sc.koolearn.com/fen/service-centre/map/广西壮族自治区"
                        >广西
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            target="_blank"
                            href="//sc.koolearn.com/fen/service-centre/map/海南省"
                        >海南
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            target="_blank"
                            href="//sc.koolearn.com/fen/service-centre/map/重庆市"
                        >重庆
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            target="_blank"
                            href="//sc.koolearn.com/fen/service-centre/map/四川省"
                        >四川
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            target="_blank"
                            href="//sc.koolearn.com/fen/service-centre/map/贵州省"
                        >贵州
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            target="_blank"
                            href="//sc.koolearn.com/fen/service-centre/map/云南省"
                        >云南
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            target="_blank"
                            href="//sc.koolearn.com/fen/service-centre/map/西藏自治区"
                        >西藏
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            target="_blank"
                            href="//sc.koolearn.com/fen/service-centre/map/陕西省"
                        >陕西
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            target="_blank"
                            href="//sc.koolearn.com/fen/service-centre/map/甘肃省"
                        >甘肃
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            target="_blank"
                            href="//sc.koolearn.com/fen/service-centre/map/青海省"
                        >青海
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            target="_blank"
                            href="//sc.koolearn.com/fen/service-centre/map/宁夏回族自治区"
                        >宁夏
                        </a>
                    </dd>
                    <dd>
                        <a
                            className={cx('link')}
                            target="_blank"
                            href="//sc.koolearn.com/fen/service-centre/map/新疆维吾尔自治区"
                        >新疆
                        </a>
                    </dd>
                </dl>
            </div>
            <div className={cx('friends-link-wrap')}>
                <div className={cx('links-list', { hidden: !isShowMoreLink })}>
                    <span className={cx('title')}>友情链接：</span>
                    <a
                        className={cx('link')}
                        href="http://edu.qq.com/"
                        target="_blank"
                    >腾讯教育
                    </a>
                    <a
                        className={cx('link')}
                        href="http://edu.163.com/"
                        target="_blank"
                    >网易教育
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.51test.net/"
                        target="_blank"
                    >无忧考网
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.exam8.com/"
                        target="_blank"
                    >考试吧
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.kaoyan.com/"
                        target="_blank"
                    >考研帮
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.kekenet.com/"
                        target="_blank"
                    >可可英语
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.offcn.com/"
                        target="_blank"
                    >公务员考试网
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.tingroom.com/"
                        target="_blank"
                    >在线英语听力室
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.zxxk.com/"
                        target="_blank"
                    >中学学科网
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.ichacha.net/"
                        target="_blank"
                    >在线翻译
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.docin.com/"
                        target="_blank"
                    >豆丁网
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.tingclass.net/"
                        target="_blank"
                    >听力课堂
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.chinakaoyan.com/"
                        target="_blank"
                    >中国考研网
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.xdf.cn/"
                        target="_blank"
                    >新东方官网
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.etest8.com/"
                        target="_blank"
                    >易考吧
                    </a>
                    <a
                        className={cx('link')}
                        href="https://kaoyan.koolearn.com/"
                        target="_blank"
                    >考研
                    </a>
                    <a
                        className={cx('link')}
                        href="https://www.51zhishang.com/cjkj/"
                        target="_blank"
                    >职上网会计
                    </a>
                    <a
                        className={cx('link')}
                        href="https://www.51zhishang.com/zckj/"
                        target="_blank"
                    >职上网注册会计师
                    </a>
                    <a
                        className={cx('link')}
                        href="https://www.51zhishang.com/zjjjs/"
                        target="_blank"
                    >职上网经济师
                    </a>
                    <a
                        className={cx('link')}
                        href="https://www.51zhishang.com/zhengquan/"
                        target="_blank"
                    >职上网证券
                    </a>
                    <a
                        className={cx('link')}
                        href="https://www.51zhishang.com/jijin/"
                        target="_blank"
                    >职上网基金
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.lizhi.fm/"
                        target="_blank"
                    >有声小说
                    </a>
                    <a
                        className={cx('link')}
                        href="https://www.ximalaya.com"
                        target="_blank"
                    >听小说
                    </a>
                    <a
                        className={cx('link')}
                        href="https://www.houxue.com/"
                        target="_blank"
                    >厚学网
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.gaosan.com/"
                        target="_blank"
                    >高三网
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.kanzhun.com"
                        target="_blank"
                    >看准网
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.hqwx.com/"
                        target="_blank"
                    >环球网校
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.leleketang.com"
                        target="_blank"
                    >乐乐课堂
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.64365.com"
                        target="_blank"
                    >律师
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.gjgwy.org/"
                        target="_blank"
                    >公务员考试
                    </a>
                    <a
                        className={cx('link')}
                        href="http://union.koolearn.com"
                        target="_blank"
                    >教育CPS联盟
                    </a>
                    <a
                        className={cx('link')}
                        href="http://china.findlaw.cn"
                        target="_blank"
                    >法律咨询
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.gaodun.com"
                        target="_blank"
                    >高顿网校
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.huibo.com"
                        target="_blank"
                    >重庆招聘网
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.1010jiajiao.com"
                        target="_blank"
                    >精英家教网
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.examw.com/"
                        target="_blank"
                    >中华考试网
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.gjgwy.net/"
                        target="_blank"
                    >国家公务员考试
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.zgjsks.com/"
                        target="_blank"
                    >教师网
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.thea.cn/"
                        target="_blank"
                    >教育联展网
                    </a>
                    <a
                        className={cx('link')}
                        href="http://tool.xdf.cn/"
                        target="_blank"
                    >学习工具
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.koolearn.com/shiti/list-2-1-0-1.html"
                        target="_blank"
                    >试题
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.51zhishang.com/"
                        target="_blank"
                    >职上网
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.eoffcn.com/"
                        target="_blank"
                    >中公网校
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.shangxueba.com"
                        target="_blank"
                    >上学吧
                    </a>
                    <a
                        className={cx('link')}
                        href="http://class.qq.com/koolearn"
                        target="_blank"
                    >腾讯精品课
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.kongfz.com/"
                        target="_blank"
                    >孔夫子图书网
                    </a>
                    <a
                        className={cx('link')}
                        href="http://www.51pigai.com/"
                        target="_blank"
                    >新东方批改网
                    </a>
                </div>
                {!isShowMoreLink &&
                <span
                    className={cx('show-more-btn')}
                    onClick={() => setIsShowMoreLink(true)}
                >更多
                </span>}
            </div>
            <div className={cx('other-info')}>
                <a
                    className={cx('link')}
                    rel="nofollow"
                    href="https://www.koolearn.com/about/"
                    target="blank"
                >关于我们
                </a>
                <a
                    className={cx('link')}
                    rel="nofollow"
                    href="https://www.koolearn.com/about/shangwu/"
                    target="_blank"
                >商务合作
                </a>
                <a
                    className={cx('link')}
                    rel="nofollow"
                    href="https://www.koolearn.com/about/guanggao/"
                    target="_blank"
                >广告服务
                </a>
                <a
                    className={cx('link')}
                    rel="nofollow"
                    href="https://sc.koolearn.com/"
                    target="_blank"
                >线下体验店
                </a>
                <a
                    className={cx('link')}
                    rel="nofollow"
                    href="https://sc.koolearn.com/acclogin"
                    target="_blank"
                >代理商入口
                </a>
                <a
                    className={cx('link')}
                    rel="nofollow"
                    href="https://help.koolearn.com/"
                    target="_blank"
                >客服中心
                </a>
                <a
                    className={cx('link')}
                    rel="nofollow"
                    href="https://www.koolearn.com/about/hezuo/"
                    target="_blank"
                >合作伙伴
                </a>
                <a
                    className={cx('link')}
                    rel="nofollow"
                    href="https://www.koolearn.com/about/lianxi/"
                    target="_blank"
                >联系我们
                </a>
                <a
                    className={cx('link')}
                    rel="nofollow"
                    href="http://zhaopin.koolearn.com/"
                    target="_blank"
                >人员招聘
                </a>
                {/* <a
                    className={cx('link')}
                    rel="nofollow"
                    href="https://www.koolearn.com/sitemap/"
                    target="_blank"
                >网站地图
                </a> */}
                <a
                    className={cx('link')}
                    href="https://union.koolearn.com/"
                    target="_blank"
                >网盟合作
                </a>
                <a
                    className={cx('link')}
                    href="https://news.koolearn.com/"
                    target="_blank"
                >资讯站
                </a>
            </div>
            <div className={cx('certification-Info')}>
                <a
                    className={cx('link')}
                    href="https://daxueui-oss.koocdn.com/images/fe_upload/2020/10/2020-10-27-1603772603441.pdf"
                    target="_blank"
                >京ICP证050421号
                </a>
                <a
                    className={cx('link')}
                    href="https://beian.miit.gov.cn"
                    target="_blank"
                >京ICP备05067669号-13
                </a>
                {/* <span className={cx('text')}>京公网安备11010802017616号</span> */}
                <a
                    target="_blank"
                    href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=11010802035547"
                    className={cx('netSecurityCode')}
                >
                    <img src="https://daxueui-oss.koocdn.com/images/fe_upload/2021/7/2021-7-29-1627541502266.jpg"/>
                    <span className="text-style">京公网安备 11010802035547号</span>
                </a>
                <a
                    className={cx('link')}
                    href="//daxueui-oss.koocdn.com/images/fe_upload/2021/12/2021-12-16-1639659765825.pdf"
                    target="_blank"
                >网络视听许可证
                </a>
                <a
                    className={cx('link')}
                    href="https://daxueui-cos.koocdn.com/images/fe_upload/2020/10/2020-10-27-1603772695667.pdf"
                    target="_blank"
                >京网文(2019)2781-276号
                </a>
                <a
                    className={cx('link')}
                    href="https://daxueui-oss.koocdn.com/images/fe_upload/2021/5/2021-5-25-1621935316498.png"
                    target="_blank"
                >营业执照
                </a>
                {
                    showApologize
                        ?
                        <a
                            className={cx('link')}
                            href="https://daxueui-oss.koocdn.com/images/fe_upload/2021/7/2021-7-5-1625474940280.pdf"
                            target="_blank"
                        >致歉声明
                        </a>
                        : null
                }
                <p>Copyright © 2011-2020 北京新东方迅程网络科技股份有限公司, All Rights Reserved</p>
                <p>违法和不良信息举报电话: 010-81401500 举报邮箱: sec@xdfzx.com&nbsp;
                    <a
                        className={cx('link')}
                        href="https://www.12377.cn/"
                        target="_blank"
                    >网上有害信息举报专区
                    </a>
                </p>
            </div>
        </div>
    );
}
